### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by chetand** [wimleers/fileconveyor#149]
Had setup Fileconveyor and it was running allright (on Rackspace UK). But now am getting the below error on running: screen python src/fileconveyor/fileconveyor/arbitrator.py

Any guidance would be highly appreciated

---------- Error ----------------
Exception in thread ArbitratorThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "src/fileconveyor/fileconveyor/arbitrator.py", line 273, in run
    self.__setup()
  File "src/fileconveyor/fileconveyor/arbitrator.py", line 235, in __setup
    self.pipeline_queue.put(item)
  File "/root/src/fileconveyor/fileconveyor/persistent_queue.py", line 103, in put
    self.dbcur.execute("INSERT INTO %s (item, key) VALUES(?, ?)" % (self.table), (sqlite3.Binary(pickled_item), md5))
OperationalError: database is locked

**Comment by ghost** [comment]
I am also facing the same issue.
@chetand Were you able to find the solution?
