### ISSUE TITLE
DeprecationWarning: (from sets import Set, ImmutableSet)

### ISSUE THREAD

**Issue by rootAmeen** [wimleers/fileconveyor#174]
I'm having this error when running arbitrator.py:

==============

root@node [~/src/fileconveyor/fileconveyor]# python arbitrator.py
/root/src/fileconveyor/fileconveyor/filter.py:10: DeprecationWarning: the sets module is deprecated
  from sets import Set, ImmutableSet
Traceback (most recent call last):
  File "arbitrator.py", line 31, in <module>
    from transporters.transporter import Transporter, ConnectionError
  File "/root/src/fileconveyor/fileconveyor/transporters/transporter.py", line 10, in <module>
    from django.core.files.storage import Storage
  File "/usr/lib/python2.6/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
SyntaxError: invalid syntax
=============

Please assist.

**Comment by rootAmeen** [comment]
Solution: Use Python 2.7+
