### ISSUE TITLE
8-bit bytestrings vs. Unicode strings in Python: fix this once and for all

### ISSUE THREAD

**Issue by haleagar** [wimleers/fileconveyor#62]
I've seen issue #25 and gotten the most recent version with the related update, but I'm still getting similar errors still however now in arbitrator.py
I belive this is one of the problem files WoodyHallæ°åç_0.jpg
Python 2.6.5
Ubuntu 10.04.1 LTS

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "arbitrator.py", line 289, in run
    self.__process_db_queue()
  File "arbitrator.py", line 634, in __process_db_queue
    self.dbcur.execute("SELECT COUNT(*) FROM synced_files WHERE input_file=? AND server=?", (input_file, server))
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by insparrow** [comment]
I haven't been able to resolve the `UnicodeDecodeError` issue. However, a few grey hairs later I was able to come up with a good enough workaround (for my use case) which has enabled me to use File Conveyor with Rackspace Cloud Files.

For my server setup (Ubuntu 10.04, Python 2.6.5 and latest File Conveyor), I encountered two `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 2: ordinal not in range(128)` issues.

**First issue**: The daemon would throw an exception before it attempted to transfer _any_ files. If you encounter the same problem, check your server's locale settings with `locale`. I wish I had checked this first! When I ran `locale`, the following errors were reported:

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```

Adding `export LC_ALL="en_US.UTF-8"` to the server's .bashrc file resolved the issues reported by `locale` **and** File Conveyor would then (in part) work.

**Second issue**: The daemon would throw an exception when it attempted to transfer a filename which contained special characters. I tried in vain to fix this but I was unsuccessful (until today I hadn't written a single line of python code). 

Creating a solution that worked with Rackspace Cloud Files was non-negotiable, so I set out to create an acceptable workaround for a Drupal 7 site that has over 50GB of images. I patched `arbitrator.py` to skip files that I knew would cause the daemon to thrown an exception:

``` python
diff --git a/fileconveyor/arbitrator.py b/fileconveyor/arbitrator.py
index 394b4b4..6fa3e5a 100644
--- a/fileconveyor/arbitrator.py
+++ b/fileconveyor/arbitrator.py
@@ -347,6 +347,7 @@ class Arbitrator(threading.Thread):
         while self.discover_queue.qsize() > 0:


             # Discover queue -> pipeline queue.
             (input_file, event) = self.discover_queue.get()
             item = self.pipeline_queue.get_item_for_key(key=input_file)
             # If the file does not yet exist in the pipeline queue, put() it.
@@ -400,6 +401,16 @@ class Arbitrator(threading.Thread):
             (input_file, event) = self.filter_queue.get()
             self.lock.release()


+            # Skip filenames which we know will not work with File Convyeor or the CDN module.
+            import re
+            path, filename = os.path.split(input_file)
+            regexp = re.compile(r'^[a-zA-Z0-9_ .-]+$')
+            if regexp.search(filename) is None:
+                import codecs
+                output_file = codecs.open('skipped_files.txt', 'a', 'utf8')
+                output_file.write(input_file + '\n')
+                continue
+
             # The file may have already been deleted, e.g. when the file was
             # moved from the pipeline list into the pipeline queue after the
             # application was interrupted. When that's the case, drop the
```

With this patch in, the daemon doesn't throw an exception and will transfer the files that it is able to transfer. The patch also logs the problematic files to `skipped_files.txt` which gives me / the client a list to fix. For a Drupal 7 site, [the transliteration module](https://www.drupal.org/project/transliteration) gives you the option to bulk rename files. I have installed this onto the site I'm working with to take care of _new_ files. The bulk rename function doesn't work for me but I believe that's an isolated issue related to the images stored in complex parent and child field collections.
